config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :users, only: %i[index show]
  resources :follows
  resources :likes, except: %i[new]
  resources :comments, except: %i[new]
  resources :posts

  post '/graphiql/graphql', to: 'graphql#execute'  
  # if Rails.env.development?
  #   mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "graphql#execute"
  # end

  devise_for :user
  authenticate :user, ->(u) { u.role_is?('admin') } do
    mount Blazer::Engine, at: 'blazer', as: 'blazer'
    # mount Sidekiq::Web => 'sidekiq', as: 'sidekiq'
    mount RailsAdmin::Engine => 'admin', as: 'rails_admin'
    mount GraphiQL::Rails::Engine, at: '/graphiql', graphql_path: 'graphql#execute'
    mount RailsPerformance::Engine, at: 'site_performance', as: 'site_performance'
  end

  post 'set_theme', to: 'home#set_theme', as: 'set_theme'
  post 'act_as_normal', to: 'home#act_as_normal', as: 'act_as_normal'
  get 'home/index'
  get 'home/about'
  get 'home/contact'
  root to: "home#index"
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  visitable :ahoy_visit

  belongs_to :user
  belongs_to :post
  validates_presence_of :user, :post, :body
  validates :body, length: { minimum: 1, maximum: 3000 }

  rails_admin do
    object_label_method do
      :body
    end

    list do
      field :id
      field :body
      field :user
      field :post
      field :created_at
      field :updated_at
    end

    show do
      field :id
      field :body
      field :user
      field :post
      field :created_at
      field :updated_at
    end

    create do
      field :body
      field :user
      field :post
    end

    update do
      field :body
      field :user
      field :post
    end
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]
  load_and_authorize_resource

  # GET /comments or /comments.json
  def index
    if can? :read, Comment
      @comments = @user_param ? @user_param.comments.includes(:user, :post).desc.page(params[:page]) : Comment.includes(:user, :post).desc.page(params[:page])
    else
      head :forbidden
    end
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
    if can? :create, @comment
      render :new
    else
      head :forbidden
    end
  end

  # GET /comments/1/edit
  def edit
    if can? :edit, @comment
      render :edit
    else
      head :forbidden
    end
  end

  # POST /comments or /comments.json
  def create
    @comment = Comment.new(comment_params)
    if can? :create, @comment
      @post = Post.find_by_id(@comment.post_id) if @comment&.post_id
      respond_to do |format|
        if @comment.save
          if @post.present?
            format.html { redirect_to @post, notice: "Comment was successfully created." }
          else
            format.html { redirect_to @comment, notice: "Comment was successfully created." }
          end
          format.json { render :show, status: :created, location: @comment }
        else
          if @post.present?
            format.html { redirect_to @post, alert: "Comment failed to create." }
          else
            format.html { render :new, status: :unprocessable_entity }
          end
          format.json { render json: @comment.errors, status: :unprocessable_entity }
        end
      end
    else
      head :forbidden
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    if can? :update, @comment
      respond_to do |format|
        if @comment.update(comment_params)
          format.html { redirect_to @comment, notice: "Comment was successfully updated." }
          format.json { render :show, status: :ok, location: @comment }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @comment.errors, status: :unprocessable_entity }
        end
      end
    else
      head :forbidden
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    if can? :destroy, @comment
      @comment.destroy
      respond_to do |format|
        format.html { redirect_to comments_url, notice: "Comment was successfully destroyed." }
        format.json { head :no_content }
      end
    else
      head :forbidden
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      if can? :read, Comment
        @comment = Comment.find(params[:id])
      else
        head :forbidden
      end
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:body, :post_id).merge(user_id: current_user.id)
    end
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: comment) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>
  <% if comment&.id %>
    <div class="field">
      <strong>Post:</strong>
      <%= link_to post_path(comment.post), class: 'hvr-bob' do %><%= comment.post.title %><% end %>
    </div>
  <% end %>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<% content_for :title, 'Editing Comment' %>
<div class="jumbotron p-1">
  <h1 class="hvr-grow">Editing Comment</h1>
</div>
<div class="container mt-4 mb-5">
  <div class="row justify-content-center text-center">
    <div class="col-12">
      <%= render 'form', comment: @comment %>
    </div>
  </div>
  <div class="row justify-content-center text-center">
    <%= link_to 'Show', @comment, class: "btn btn-sm btn-warning" if can? :read, @comment %> |
    <%= link_to 'Back', comments_path, class: "btn btn-sm btn-secondary" %>
  </div>
</div>

app/views/comments/index.html.erb
<% content_for :title, 'Comments' %>
<div class="jumbotron p-1">
  <h1 class="hvr-grow">Comments</h1>
  <% if current_user&.id %>
    <h6>
      <form><input type="hidden" name="user_filter" value="<%= @user_param ? nil : current_user.id %>"><button type="submit" class="btn btn-sm btn-info"><%=@user_param ? 'All' : 'My Comments' %></button></form>
    </h6>
  <% end %>
</div>
<% if can? :read, @comments %>
  <div class="container mt-4 mb-5">
    <div class="row justify-content-center text-center">
      <div class="col-12">
        <table class="table table-hover table-striped  <%= @dark_mode ? 'table-dark ' :  '' %>">
          <thead class="thead-dark">
            <tr>
              <th>Body</th>
              <th>User</th>
              <th>Post</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @comments.each do |comment| %>
              <tr>
                <td><%= comment.body %></td>
                <td>By: <%= link_to user_path(comment.user), class: 'hvr-glow' do %><%= comment.user.email %><% end %></td>
                <td><%= link_to post_path(comment.post), class: 'hvr-bob' do %><%= comment.post.title %><% end %></td>
                <td><%= link_to 'Show', comment, class: "btn btn-sm btn-warning" if can? :read, comment %></td>
                <td><%= link_to 'Edit', edit_comment_path(comment), class: "btn btn-sm btn-success" if can? :update, comment %></td>
                <td><%= link_to 'Destroy', comment, class: "btn btn-sm btn-danger", method: :delete, data: { confirm: 'Are you sure?' } if can? :destroy, comment %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
    <hr>
    <div class="row justify-content-center text-center">
      <%= paginate @comments, window: 2 if @comments.any? %>
    </div>
  </div>
<% end %>

app/views/comments/new.html.erb
<% content_for :title, 'New Comment' %>
<div class="jumbotron p-1">
  <h1 class="hvr-grow">New Comment</h1>
</div>
<div class="container mt-4 mb-5">
  <div class="row justify-content-center text-center">
    <div class="col-12">
      <%= render 'form', comment: @comment %>
    </div>
  </div>
  <div class="row justify-content-center text-center">
    <%= link_to 'Back', comments_path, class: "btn btn-sm btn-secondary" %>
  </div>
</div>

app/views/comments/show.html.erb
<% content_for :title, 'Comment' %>
<div class="jumbotron p-1">
  <h1 class="hvr-grow">Comment</h1>
</div>
<% if can? :read, @comment %>
  <div class="container mt-4 mb-5">
    <div class="row justify-content-center text-center">
      <div class="col-6 m-1  border rounded shadow p-1 pt-3">
        <h2 class="mb-4">
          <strong>Body:</strong>
          <%= @comment.body %>
        </h2>
        <p>
          <strong>User:</strong>
          <%= link_to user_path(@comment.user), class: 'hvr-glow' do %><%= @comment.user.email %><% end %>
        </p>
        <p>
          <strong>Post:</strong>
          <%= link_to post_path(@comment.post), class: 'hvr-bob' do %><%= @comment.post.title %><% end %>
        </p>
      </div>
      <div class="col-5 m-1 border rounded shadow p-1 pt-3">
        <h3 class="mb-3">Post:</h3>
        <div>
          <h5 class="mb-4">
            <strong>Title:</strong>
            <%= @comment.post.title %>
          </h5>
          <p>
            <strong>Body:</strong>
            <%= @comment.post.body %>
          </p>
          <p>
            <strong>User:</strong>
            By: <%= link_to user_path(@comment.post.user), class: 'hvr-glow' do %><%= @comment.post.user.email %><% end %>
          </p>
        </div>
      </div>
    </div>
    <hr>
    <div class="row justify-content-center text-center">
      <%= link_to 'Edit', edit_comment_path(@comment), class: "btn btn-sm btn-success" if can? :update, @comment  %> |
      <%= link_to 'Back', comments_path, class: "btn btn-sm btn-secondary" %>
    </div>
  </div>
<% end %>