config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :users, only: %i[index show]
  resources :follows
  resources :likes, except: %i[new]
  resources :comments, except: %i[new]
  resources :posts

  post '/graphiql/graphql', to: 'graphql#execute'  
  # if Rails.env.development?
  #   mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "graphql#execute"
  # end

  devise_for :user
  authenticate :user, ->(u) { u.role_is?('admin') } do
    mount Blazer::Engine, at: 'blazer', as: 'blazer'
    # mount Sidekiq::Web => 'sidekiq', as: 'sidekiq'
    mount RailsAdmin::Engine => 'admin', as: 'rails_admin'
    mount GraphiQL::Rails::Engine, at: '/graphiql', graphql_path: 'graphql#execute'
    mount RailsPerformance::Engine, at: 'site_performance', as: 'site_performance'
  end

  post 'set_theme', to: 'home#set_theme', as: 'set_theme'
  post 'act_as_normal', to: 'home#act_as_normal', as: 'act_as_normal'
  get 'home/index'
  get 'home/about'
  get 'home/contact'
  root to: "home#index"
end

app/models/like.rb
# frozen_string_literal: true

class Like < ApplicationRecord
  visitable :ahoy_visit

  belongs_to :user
  belongs_to :post
  validates_presence_of :user, :post
  validates :user, uniqueness: { scope: :post }

  scope :is_likes, -> { where(is_like: true) }
  scope :is_dislikes, -> { where(is_like: false) }

  rails_admin do
    object_label_method do
      :is_like
    end

    list do
      field :id
      field :is_like
      field :user
      field :post
      field :created_at
      field :updated_at
    end

    show do
      field :id
      field :is_like
      field :user
      field :post
      field :created_at
      field :updated_at
    end

    create do
      field :is_like
      field :user
      field :post
    end

    update do
      field :is_like
      field :user
      field :post
    end
  end
end

app/controllers/likes_controller.rb
# frozen_string_literal: true

class LikesController < ApplicationController
  before_action :set_like, only: %i[ show edit update destroy ]
  load_and_authorize_resource

  # GET /likes or /likes.json
  def index
    if can? :read, Like
      @likes = @user_param ? @user_param.likes.includes(:user, :post).desc.page(params[:page]) : Like.includes(:user, :post).desc.page(params[:page])
    else
      head :forbidden
    end
  end

  # GET /likes/1 or /likes/1.json
  def show
  end

  # GET /likes/new
  def new
    @like = Like.new
    if can? :create, @like
      render :new
    else
      head :forbidden
    end
  end

  # GET /likes/1/edit
  def edit
    if can? :edit, @like
      render :edit
    else
      head :forbidden
    end
  end

  # POST /likes or /likes.json
  def create
    @like = Like.new(like_params)
    if can? :create, @like
      @post = Post.find_by_id(@like.post_id) if @like&.post_id
      respond_to do |format|
        if @like.save
          if @post.present?
            format.html { redirect_to @post, notice: "Like was successfully created." }
          else
            format.html { redirect_to @like, notice: "Like was successfully created." }
          end
          format.json { render :show, status: :created, location: @like }
        else
          if @post.present?
            format.html { redirect_to @post, alert: "Like failed to create." }
          else
            format.html { render :new, status: :unprocessable_entity }
          end
          format.json { render json: @like.errors, status: :unprocessable_entity }
        end
      end
    else
      head :forbidden
    end
  end

  # PATCH/PUT /likes/1 or /likes/1.json
  def update
    if can? :update, @like
      @post = Post.find_by_id(@like.post_id) if @like&.post_id
      is_like = @like.is_like ? "true" : "false"
      respond_to do |format|
        if (@post.present? && like_params[:is_like] == is_like) || @like.update(like_params)
          if @post.present?
            if like_params[:is_like] == is_like
              @like.destroy
              msg = "Like was successfully destroyed."
            else
              msg = "Like was successfully updated."
            end
            format.html { redirect_to @post, notice: msg }
          else
            format.html { redirect_to @like, notice: "Like was successfully updated." }
          end
          format.json { render :show, status: :ok, location: @like }
        else
          if @post.present?
            format.html { redirect_to @post, alert: "Like failed to update." }
          else
            format.html { render :edit, status: :unprocessable_entity }
          end
          format.json { render json: @like.errors, status: :unprocessable_entity }
        end
      end
    else
      head :forbidden
    end
  end

  # DELETE /likes/1 or /likes/1.json
  def destroy
    if can? :destroy, @like
      @like.destroy
      respond_to do |format|
        format.html { redirect_to likes_url, notice: "Like was successfully destroyed." }
        format.json { head :no_content }
      end
    else
      head :forbidden
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_like
      if can? :read, Like
        @like = Like.find(params[:id])
      else
        head :forbidden
      end
    end

    # Only allow a list of trusted parameters through.
    def like_params
      params.require(:like).permit(:is_like, :post_id, :user_id).merge(user_id: current_user.id)
    end
end

app/helpers/likes_helper.rb
# frozen_string_literal: true

module LikesHelper
end

app/views/likes/_form.html.erb
<%= form_with(model: like) do |form| %>
  <% if like.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(like.errors.count, "error") %> prohibited this like from being saved:</h2>
      <ul>
        <% like.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :is_like %>
    <%= form.check_box :is_like %>
  </div>
  <% if like&.id %>
    <div class="field">
      <strong>Post:</strong>
      <%= link_to post_path(like.post), class: 'hvr-bob' do %><%= like.post.title %><% end %>
    </div>
  <% end %>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
<hr>

app/views/likes/edit.html.erb
<% content_for :title, 'Editing Like' %>
<div class="jumbotron p-1">
  <h1 class="hvr-grow">Editing Like</h1>
</div>
<div class="container mt-4 mb-5">
  <div class="row justify-content-center text-center">
    <div class="col-12">
      <%= render 'form', like: @like %>
    </div>
  </div>
  <div class="row justify-content-center text-center">
    <%= link_to 'Show', @like, class: "btn btn-sm btn-warning" if can? :read, @like %> |
    <%= link_to 'Back', likes_path, class: "btn btn-sm btn-secondary" %>
  </div>
</div>

app/views/likes/index.html.erb
<% content_for :title, 'Likes' %>
<div class="jumbotron p-1">
  <h1 class="hvr-grow">Likes</h1>
  <% if current_user&.id %>
    <h6>
      <form><input type="hidden" name="user_filter" value="<%= @user_param ? nil : current_user.id %>"><button type="submit" class="btn btn-sm  btn-info"><%=@user_param ? 'All' : 'My Likes' %></button></form>
    </h6>
  <% end %>
</div>
<% if can? :read, @like %>
  <div class="container mt-4 mb-5">
    <div class="row justify-content-center text-center">
      <div class="col-12">
        <table class="table table-hover table-striped  <%= @dark_mode ? 'table-dark ' :  '' %>">
          <thead class="thead-dark">
            <tr>
              <th>Is Like</th>
              <th>User</th>
              <th>Post</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @likes.each do |like| %>
              <tr>
                <td><%= like.is_like %></td>
                <td>By: <%= link_to user_path(like.user), class: 'hvr-glow' do %><%= like.user.email %><% end %></td>
                <td><%= link_to post_path(like.post), class: 'hvr-bob' do %><%= like.post.title %><% end %></td>
                <td><%= link_to 'Show', like, class: "btn btn-sm btn-warning" if can? :read, like %></td>
                <td><%= link_to 'Edit', edit_like_path(like), class: "btn btn-sm btn-success" if can? :update, like %></td>
                <td><%= link_to 'Destroy', like, class: "btn btn-sm btn-danger", method: :delete, data: { confirm: 'Are you sure?' } if can? :update, like %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
    <hr>
    <div class="row justify-content-center text-center">
      <%= paginate @likes, window: 2 if @likes.any? %>
    </div>
  </div>
<% end %>

app/views/likes/new.html.erb
<% content_for :title, 'New Like' %>
<div class="jumbotron p-1">
  <h1 class="hvr-grow">New Like</h1>
</div>
<div class="container mt-4 mb-5">
  <div class="row justify-content-center text-center">
    <div class="col-12">
      <%= render 'form', like: @like %>
    </div>
  </div>
  <div class="row justify-content-center text-center">
    <%= link_to 'Back', likes_path, class: "btn btn-sm btn-secondary" %>
  </div>
</div>

app/views/likes/show.html.erb
<% content_for :title, 'Like' %>
<div class="jumbotron p-1">
  <h1 class="hvr-grow">Like</h1>
</div>
<% if can? :read, @like %>
  <div class="container mt-4 mb-5">
    <div class="row justify-content-center text-center">
      <div class="col-6 m-1  border rounded shadow p-1 pt-3">
        <h2 class="mb-4">
          <strong>Is Like:</strong>
          <%= @like.is_like %>
        </h2>
        <p>
          <strong>User:</strong>
          <%= link_to user_path(@like.user), class: 'hvr-glow' do %><%= @like.user.email %><% end %>
        </p>
        <p>
          <strong>Post:</strong>
          <%= link_to post_path(@like.post), class: 'hvr-bob' do %><%= @like.post.title %><% end %>
        </p>
      </div>
      <div class="col-5 m-1 border rounded shadow p-1 pt-3">
        <h3 class="mb-3">Post:</h3>
        <div>
          <h5 class="mb-4">
            <strong>Title:</strong>
            <%= @like.post.title %>
          </h5>
          <p>
            <strong>Body:</strong>
            <%= @like.post.body %>
          </p>
          <p>
            <strong>User:</strong>
            By: <%= link_to user_path(@like.post.user), class: 'hvr-glow' do %><%= @like.post.user.email %><% end %>
          </p>
        </div>
      </div>
    </div>
    <hr>
    <div class="row justify-content-center text-center">
      <%= link_to 'Edit', edit_like_path(@like), class: "btn btn-sm btn-success" if can? :update, @like  %> |
      <%= link_to 'Back', likes_path, class: "btn btn-sm btn-secondary" %>
    </div>
  </div>
<% end %>