config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :users, only: %i[index show]
  resources :follows
  resources :likes, except: %i[new]
  resources :comments, except: %i[new]
  resources :posts

  post '/graphiql/graphql', to: 'graphql#execute'  
  # if Rails.env.development?
  #   mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "graphql#execute"
  # end

  devise_for :user
  authenticate :user, ->(u) { u.role_is?('admin') } do
    mount Blazer::Engine, at: 'blazer', as: 'blazer'
    # mount Sidekiq::Web => 'sidekiq', as: 'sidekiq'
    mount RailsAdmin::Engine => 'admin', as: 'rails_admin'
    mount GraphiQL::Rails::Engine, at: '/graphiql', graphql_path: 'graphql#execute'
    mount RailsPerformance::Engine, at: 'site_performance', as: 'site_performance'
  end

  post 'set_theme', to: 'home#set_theme', as: 'set_theme'
  post 'act_as_normal', to: 'home#act_as_normal', as: 'act_as_normal'
  get 'home/index'
  get 'home/about'
  get 'home/contact'
  root to: "home#index"
end

app/views/shared/_footer.html.erb
<div class="container-fluid jumbotron-footer p-1 m-0">
    <div class="row justify-content-center m-0 mt-1">
        <div class="col-md-5 col-sm-10">
            <h6>LinkedIn</h6>
            <p><a href="https://www.linkedin.com/in/ahmedhamid13/">Ahmed Abdelhamid</a></p>
        </div>
        <div class="col-md-5 col-sm-10">
            <h6>GitHub</h6>
            <p><a href="https://github.com/ahmedhamid13">Ahmed Abdelhamid</a></p>
        </div>
    </div>
    <div class="row justify-content-center m-0 mt-2">
        <div class="col-12 m-0">
            <p>Website_GitHub  2021&copy; <a href="https://github.com/ahmedhamid13/college-get-together"> get-college_get_together</a></p>
        </div>
    </div>
</div>

app/views/shared/_header.html.erb
<nav class="navbar <% if @dark_mode %>navbar-dark<% else %>navbar-light<% end %> navbar-static-top navbar-expand-md">
  <div class="container">
    <%= link_to root_path, class: 'navbar-brand m-0' do %>
      <%= image_tag("favicon.ico", class: 'img-fluid m-0 hvr-grow', size: '45x45') %>
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="nav navbar-nav mr-auto">
      </ul>
      <ul class="nav navbar-nav ml-auto">
        <% if !current_user || (current_user && !current_user.role_is?("admin")) || (current_user && current_user.role_is?("admin") && @act_as_normal) %>
          <li class='nav-item mt-1'><%= link_to('Posts', posts_path, class: 'nav-link')  if can? :read, Post %></li>
          <li class='nav-item mt-1'><%= link_to('Comments', comments_path, class: 'nav-link') if can? :read, Comment %></li>
          <li class='nav-item mt-1'><%= link_to('Likes', likes_path, class: 'nav-link')  if can? :read, Like %></li>
          <li class='nav-item mt-1'><%= link_to('Users', users_path, class: 'nav-link')  if can? :read, User %></li>
        <% end %>
        <% if current_user && current_user.role_is?("admin") && !@act_as_normal %>
          <li class='nav-item mt-1'><%= link_to 'Adminstration', "/admin", class: 'nav-link border border-warning rounded' %></li>
        <% end %>
        <% if current_user %>
          <% if !current_user.role_is?("admin") || @act_as_normal %>
          <% end %>
          <li class='nav-item mt-1'>
            <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link border-danger rounded btn-md' do %>
              <%= fa_icon "sign-out-alt"%>
              <span>Sign Out</span>
            <%end%>
          </li>
        <% else %>
          <li class='nav-item mt-1'>
            <%= link_to new_user_registration_path, class: 'nav-link border-primary rounded btn-md' do %>
              <%= fa_icon "user-plus"%>
              <span>Sign Up</span>
            <%end%>
          </li>
          <li class='nav-item mt-1'>
            <%= link_to new_user_session_path, class: 'nav-link border-success rounded btn-md' do %>
              <%= fa_icon "user"%>
              <span>Login</span>
            <%end%>
          </li>
        <% end %>
        <li class='nav-item mt-2 pt-1 ml-2'>
          <%= form_with url: "/set_theme", method: :post do |form| %>
            <label class="switch">
              <input type="checkbox" name="theme_mode" <% if @dark_mode %>checked<% end %> onchange="this.form.submit()">
              <span class="slider round" <% if @dark_mode %>style='background-color: #002535;'<% end %>></span>
            </label>
            <span>Dark mode</span>
          <% end %>
        </li>
        <% if current_user && current_user.role_is?("admin") %>
          <li class='nav-item mt-2 pt-1 ml-2'>
            <%= form_with url: "/act_as_normal", method: :post do |form| %>
              <label class="switch">
                <input type="checkbox" name="as_normal" <% if @act_as_normal %>checked<% end %> onchange="this.form.submit()">
                <span class="slider round" <% if @act_as_normal %>style='background-color: #002535;'<% end %>></span>
              </label>
              <span>Act as normal user</span>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_messages.html.erb
<% flash.each do |key, value| %>
  <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
    <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
      <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
    </symbol>
    <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
      <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
    </symbol>
  </svg>

  <div id="flash-msg" class="container justify-content-center p-1 border border-2 text-center shadow rounded border alert alert-dismissible <% if (key == 'alert') || (key == 'error')%>alert-danger border-danger<% end %> <% if key == 'notice'%>alert-success  border-success<% end %> m-auto mt-3 fade show animate__animated animate__fadeIn mt-1 mb-3" role="alert">

    <% if (key == 'alert') || (key == 'error')%>
      <svg class="bi flex-shrink-0 me-2" width="24" height="24"><use xlink:href="#exclamation-triangle-fill"/></svg>
    <% end %> 
    <% if key == 'notice'%>
      <svg class="bi flex-shrink-0 me-2" width="24" height="24"><use xlink:href="#check-circle-fill"/></svg>
    <% end %>

    <span class="d-inline"><%= value %></span>
  </div>

  <script type="text/javascript">
    const flash_msg = document.getElementById('flash-msg')

    if (flash_msg){
      setTimeout(disappear, 3800);
    }

    function disappear(){
      flash_msg.classList.add("animate__fadeOut");
      setTimeout(function(){ flash_msg.style.display = 'none'; }, 500);
    }
  </script>
<% end %>

app/views/shared/_sidebar.html.erb
<div id="mySidenav" class="sidenav">  
    <%# <a href="/pnr_search" id="blog"><%= fa_icon "search" Pnr</a> %>
    <a href="/home/contact" id="contact">Contact</a>
    <a href="/home/about" id="about">About</a>
</div>