config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :users, only: %i[index show]
  resources :follows
  resources :likes, except: %i[new]
  resources :comments, except: %i[new]
  resources :posts

  post '/graphiql/graphql', to: 'graphql#execute'  
  # if Rails.env.development?
  #   mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "graphql#execute"
  # end

  devise_for :user
  authenticate :user, ->(u) { u.role_is?('admin') } do
    mount Blazer::Engine, at: 'blazer', as: 'blazer'
    # mount Sidekiq::Web => 'sidekiq', as: 'sidekiq'
    mount RailsAdmin::Engine => 'admin', as: 'rails_admin'
    mount GraphiQL::Rails::Engine, at: '/graphiql', graphql_path: 'graphql#execute'
    mount RailsPerformance::Engine, at: 'site_performance', as: 'site_performance'
  end

  post 'set_theme', to: 'home#set_theme', as: 'set_theme'
  post 'act_as_normal', to: 'home#act_as_normal', as: 'act_as_normal'
  get 'home/index'
  get 'home/about'
  get 'home/contact'
  root to: "home#index"
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  visitable :ahoy_visit

  belongs_to :user
  validates_presence_of :user, :title
  validates :title, length: { minimum: 1, maximum: 100 }
  validates :body, length: { minimum: 1, maximum: 3000 }

  has_many :comments, class_name: "Comment", foreign_key: "post_id", dependent: :destroy
  has_many :likes, class_name: "Like", foreign_key: "post_id", dependent: :destroy

  rails_admin do
    object_label_method do
      :title
    end

    list do
      field :id
      field :title
      field :body
      field :user
      field :created_at
      field :updated_at
    end

    show do
      field :id
      field :title
      field :body
      field :user
      field :comments
      field :likes
      field :created_at
      field :updated_at
    end

    create do
      field :title
      field :body
      field :user
    end

    update do
      field :title
      field :body
      field :user
    end
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  load_and_authorize_resource

  # GET /posts or /posts.json
  def index
    if can? :read, Post
      @posts = @user_param ? @user_param.posts.includes(:user, :comments, :likes).desc.page(params[:page]) : Post.includes(:user, :comments, :likes).desc.page(params[:page])
    else
      head :forbidden
    end
  end

  # GET /posts/1 or /posts/1.json
  def show
    if @post
      @comments = @post.comments.includes(:user, :post).desc.page(params[:page])
      @like = current_user.likes.find_by(post_id: @post.id) if current_user
    end
  end

  # GET /posts/new
  def new
    @post = Post.new
    if can? :create, @post
      render :new
    else
      head :forbidden
    end
  end

  # GET /posts/1/edit
  def edit
    if can? :edit, @post
      render :edit
    else
      head :forbidden
    end
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    if can? :create, @post
      respond_to do |format|
        if @post.save
          format.html { redirect_to @post, notice: "Post was successfully created." }
          format.json { render :show, status: :created, location: @post }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    else
      head :forbidden
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    if can? :update, @post
      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to @post, notice: "Post was successfully updated." }
          format.json { render :show, status: :ok, location: @post }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    else
      head :forbidden
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    if can? :destroy, @post
      @post.destroy
      respond_to do |format|
        format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
        format.json { head :no_content }
      end
    else
      head :forbidden
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      if can? :read, Post
        @post = Post.find(params[:id])
      else
        head :forbidden
      end
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body).merge(user_id: current_user.id)
    end
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/views/posts/_comment_form.html.erb
<%= form_with(model: comment) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.text_area :body, rows: 8 %>
    <%= form.hidden_field :post_id, value: post.id %>
  </div>
  <hr>
  <% if current_user&.email %>
    <div class="field border border-secondary shadow rounded mr-3 ml-3">
      By: <%= current_user.email %>
    </div>
  <% end %>
  <br>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, rows: 12 %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
<hr>

app/views/posts/_like_form.html.erb
<div class="container">
  <div class="row justify-content-center text-center">
    <% if like.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(like.errors.count, "error") %> prohibited this like from being saved:</h2>
        <ul>
          <% like.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>
  <div class="row justify-content-center text-center">
    <div class="col-5">
      <%= form_with(model: like) do |form| %>
        <div class="field">
          <%= form.hidden_field :is_like, value: true %>
          <%= form.hidden_field :post_id, value: post.id %>
        </div>
        <div class="actions">
          <%= form.submit "Like", class: "btn #{(like&.id && like.is_like) ? 'btn-success' : 'btn-outline-success'}" %>
        </div>
      <% end %>
    </div>
    <div class="col-5">
      <%= form_with(model: like) do |form| %>
        <div class="field">
          <%= form.hidden_field :is_like, value: false %>
          <%= form.hidden_field :post_id, value: post.id %>
        </div>
        <div class="actions">
          <%= form.submit "DisLike", class: "btn #{(like&.id && !like.is_like) ? 'btn-danger' : 'btn-outline-danger'}" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<% content_for :title, 'Editing Post' %>
<div class="jumbotron p-1">
  <h1 class="hvr-grow">Editing Post</h1>
</div>
<div class="container mt-4 mb-5">
  <div class="row justify-content-center text-center">
    <div class="col-12">
      <%= render 'form', post: @post %>
    </div>
  </div>
  <div class="row justify-content-center text-center">
    <%= link_to 'Show', @post, class: "btn btn-sm btn-warning" if can? :read, @post %> |
    <%= link_to 'Back', posts_path, class: "btn btn-sm btn-secondary" %>
  </div>
</div>

app/views/posts/index.html.erb
<% content_for :title, 'Posts' %>
<div class="jumbotron p-1">
  <h1 class="hvr-grow">Posts</h1>
  <% if current_user&.id %>
    <h6>
      <form><input type="hidden" name="user_filter" value="<%= @user_param ? nil : current_user.id %>"><button type="submit" class="btn btn-sm btn-info"><%=@user_param ? 'All' : 'My Posts' %></button></form>
    </h6>
  <% end %>
</div>
<% if can? :read, @posts %>
  <div class="container mt-4 mb-5">
    <div class="row justify-content-center text-center">
      <%= link_to 'New Post', new_post_path, class: "btn btn-primary" if can? :create, Post %>
    </div>
    <hr />
    <div class="row justify-content-center text-center">
      <div class="col-12">
        <table class="table table-hover table-striped  <%= @dark_mode ? 'table-dark ' :  '' %>">
          <thead class="thead-dark">
            <tr>
              <th>Title</th>
              <th>User</th>
              <th>Date</th>
              <th>Comments</th>
              <th>Likes</th>
              <th>DisLikes</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @posts.each do |post| %>
              <tr>
                <td><%= post.title %></td>
                <td>By: <%= link_to user_path(post.user), class: 'hvr-glow' do %><%= post.user.email %><% end %></td>
                <td><%= post.created_at.strftime("%m/%d/%Y At %I:%M:%S %p") %></td>
                <td><%= post.comments.size %></td>
                <td><%= post.likes.is_likes.size %></td>
                <td><%= post.likes.is_dislikes.size %></td>
                <td><%= link_to 'Show', post, class: "btn btn-sm btn-warning" if can? :read, post %></td>
                <td><%= link_to 'Edit', edit_post_path(post), class: "btn btn-sm btn-success" if can? :update, post %></td>
                <td><%= link_to 'Destroy', post, class: "btn btn-sm btn-danger", method: :delete, data: { confirm: 'Are you sure?' } if can? :destroy, post %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
    <hr>
    <div class="row justify-content-center text-center">
      <%= paginate @posts, window: 2 if @posts.any? %>
    </div>
  </div>
<% end %>

app/views/posts/new.html.erb
<% content_for :title, 'New Post' %>
<div class="jumbotron p-1">
  <h1 class="hvr-grow">New Post</h1>
</div>
<div class="container mt-4 mb-5">
  <div class="row justify-content-center text-center">
    <div class="col-12">
      <%= render 'form', post: @post %>
    </div>
  </div>
  <div class="row justify-content-center text-center">
    <%= link_to 'Back', posts_path, class: "btn btn-sm btn-secondary" %>
  </div>
</div>

app/views/posts/show.html.erb
<% content_for :title, 'Post' %>
<div class="jumbotron p-1">
  <h1 class="hvr-grow">Post</h1>
</div>
<% if can? :read, @post %>
  <div class="container mt-4 mb-5">
    <div class="row justify-content-center text-center">
      <div class="col-12 m-1  border rounded shadow p-1 pt-3">
        <h2 class="mb-4 hvr-glow">
          <strong>Title:</strong>
          <%= @post.title %>
        </h2>
        <p class="border border-dark rounded mr-4 ml-4 p-2">
          <%= @post.body %>
        </p>
        <p>
          <strong>User:</strong>
          By: <%= link_to user_path(@post.user), class: 'hvr-glow' do %><%= @post.user.email %><% end %>
        </p>
        <p>
          <strong>Created At:</strong>
          <%= @post.created_at.strftime("%m/%d/%Y At %I:%M:%S %p")%>
        </p>
      </div>
    </div>
    <div class="row justify-content-center text-center">
      <div class="col-8 m-1 border rounded shadow p-1 pt-3">
        <div>
          <p>
            <strong>Likes: </strong>
            <%= @post.likes.is_likes.size %> |
            <strong>DisLikes: </strong>
            <%= @post.likes.is_dislikes.size %>
          </p>
        </div>
        <hr />
        <div>
          <h3 class="mb-3">Comments (<%= @post.comments.size %>):</h3>
          <div class="justify-content-center text-center p-1">
            <table class="table table-sm table-hover table-striped  <%= @dark_mode ? 'table-dark ' :  '' %>">
              <thead class="thead-dark">
                <tr>
                  <th>Body</th>
                  <th>Date</th>
                  <th>User</th>
                </tr>
              </thead>
              <tbody>
                <% @comments.desc.each do |comment| %>
                  <tr>
                    <td><%= comment.body %></td>
                    <td><%= comment.created_at.strftime("%m/%d/%Y At %I:%M:%S %p") %></td>
                    <td>By: <%= comment.user.email %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
        <div class="justify-content-center text-center m-auto">
          <%= paginate @comments, window: 2 if @comments.any? %>
        </div>
      </div>
      <% if (can? :create, Comment) || (can? :create, Like) %>
        <div class="col-3 m-1 border rounded shadow p-1 pt-3">
          <% if can? :create, Like %>
            <div>
              <%= render 'like_form', like: @like || Like.new, post: @post %>
            </div>
          <% end %>
          <% if can? :create, Comment %>
            <hr>
            <h3 class="mb-4">Comment On Post</h3>
            <div>
              <%= render 'comment_form', comment: @comment || Comment.new, post: @post %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
    <hr>
    <div class="row justify-content-center text-center p-1">
      <%= link_to 'Edit', edit_post_path(@post), class: "btn btn-sm btn-success" if can? :update, @post %> |
      <%= link_to 'Back', posts_path, class: "btn btn-sm btn-secondary" %>
    </div>
  </div>
<% end %>